#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Tue Mar  8 18:27:12 2022
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class ElemProprties(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ElemProprties.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((406, 512))
        self.SetTitle("Element-Properties")

        self.panel_properties = wx.Panel(self, wx.ID_ANY)

        sizer_main = wx.BoxSizer(wx.VERTICAL)

        self.nb_properties = wx.Notebook(self.panel_properties, wx.ID_ANY)
        sizer_main.Add(self.nb_properties, 1, wx.EXPAND, 0)

        self.nb_panel_path = wx.Panel(self.nb_properties, wx.ID_ANY)
        self.nb_properties.AddPage(self.nb_panel_path, "Path")

        sizer_path = wx.BoxSizer(wx.VERTICAL)

        sizer_id_1 = wx.StaticBoxSizer(wx.StaticBox(self.nb_panel_path, wx.ID_ANY, "Id"), wx.HORIZONTAL)
        sizer_path.Add(sizer_id_1, 0, wx.EXPAND, 0)

        self.txt_id = wx.TextCtrl(self.nb_panel_path, wx.ID_ANY, "")
        self.txt_id.SetToolTip("Id of element")
        sizer_id_1.Add(self.txt_id, 1, 0, 0)

        lbl_preview_1 = wx.StaticText(self.nb_panel_path, wx.ID_ANY, "Preview", style=wx.ALIGN_CENTER_HORIZONTAL)
        lbl_preview_1.SetMinSize((80, -1))
        sizer_id_1.Add(lbl_preview_1, 0, wx.ALL, 0)

        sizer_stroke_1 = wx.StaticBoxSizer(wx.StaticBox(self.nb_panel_path, wx.ID_ANY, "Stroke"), wx.VERTICAL)
        sizer_path.Add(sizer_stroke_1, 0, wx.EXPAND, 0)

        sizer_stroke_width_1 = wx.StaticBoxSizer(wx.StaticBox(self.nb_panel_path, wx.ID_ANY, "Width"), wx.HORIZONTAL)
        sizer_stroke_1.Add(sizer_stroke_width_1, 0, wx.EXPAND, 0)

        self.cbo_width = wx.ComboBox(self.nb_panel_path, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        self.cbo_width.SetToolTip("Width of stroke")
        sizer_stroke_width_1.Add(self.cbo_width, 1, 0, 0)

        sizer_color_stroke_1 = wx.StaticBoxSizer(wx.StaticBox(self.nb_panel_path, wx.ID_ANY, "Color"), wx.HORIZONTAL)
        sizer_stroke_1.Add(sizer_color_stroke_1, 1, wx.EXPAND, 0)

        self.btn_col_stroke_1_1 = wx.Button(self.nb_panel_path, wx.ID_ANY, "None")
        self.btn_col_stroke_1_1.SetMinSize((45, 45))
        self.btn_col_stroke_1_1.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.btn_col_stroke_1_1.SetFont(wx.Font(5, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.btn_col_stroke_1_1.SetToolTip("Choose no color")
        sizer_color_stroke_1.Add(self.btn_col_stroke_1_1, 1, 0, 0)

        self.btn_col_stroke_2_1 = wx.Button(self.nb_panel_path, wx.ID_ANY, "Red")
        self.btn_col_stroke_2_1.SetMinSize((45, 45))
        self.btn_col_stroke_2_1.SetBackgroundColour(wx.Colour(255, 0, 0))
        self.btn_col_stroke_2_1.SetFont(wx.Font(5, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.btn_col_stroke_2_1.SetToolTip("Choose red color")
        sizer_color_stroke_1.Add(self.btn_col_stroke_2_1, 1, 0, 0)

        self.btn_col_stroke_3_1 = wx.Button(self.nb_panel_path, wx.ID_ANY, "Green")
        self.btn_col_stroke_3_1.SetMinSize((45, 45))
        self.btn_col_stroke_3_1.SetBackgroundColour(wx.Colour(0, 255, 0))
        self.btn_col_stroke_3_1.SetFont(wx.Font(5, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.btn_col_stroke_3_1.SetToolTip("Choose green color")
        sizer_color_stroke_1.Add(self.btn_col_stroke_3_1, 1, 0, 0)

        self.btn_col_stroke_4_1 = wx.Button(self.nb_panel_path, wx.ID_ANY, "Blue")
        self.btn_col_stroke_4_1.SetMinSize((45, 45))
        self.btn_col_stroke_4_1.SetBackgroundColour(wx.Colour(0, 0, 255))
        self.btn_col_stroke_4_1.SetFont(wx.Font(5, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.btn_col_stroke_4_1.SetToolTip("Choose blue color")
        sizer_color_stroke_1.Add(self.btn_col_stroke_4_1, 1, 0, 0)

        self.btn_col_stroke_5_1 = wx.Button(self.nb_panel_path, wx.ID_ANY, "Yellow")
        self.btn_col_stroke_5_1.SetMinSize((45, 45))
        self.btn_col_stroke_5_1.SetBackgroundColour(wx.Colour(255, 255, 0))
        self.btn_col_stroke_5_1.SetFont(wx.Font(5, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.btn_col_stroke_5_1.SetToolTip("Choose yellow color")
        sizer_color_stroke_1.Add(self.btn_col_stroke_5_1, 1, 0, 0)

        self.btn_col_stroke_6_1 = wx.Button(self.nb_panel_path, wx.ID_ANY, "Pink")
        self.btn_col_stroke_6_1.SetMinSize((45, 45))
        self.btn_col_stroke_6_1.SetBackgroundColour(wx.Colour(255, 0, 255))
        self.btn_col_stroke_6_1.SetFont(wx.Font(5, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.btn_col_stroke_6_1.SetToolTip("Choose pink color")
        sizer_color_stroke_1.Add(self.btn_col_stroke_6_1, 1, 0, 0)

        self.btn_col_stroke_7_1 = wx.Button(self.nb_panel_path, wx.ID_ANY, "Cyan")
        self.btn_col_stroke_7_1.SetMinSize((45, 45))
        self.btn_col_stroke_7_1.SetBackgroundColour(wx.Colour(0, 255, 255))
        self.btn_col_stroke_7_1.SetFont(wx.Font(5, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.btn_col_stroke_7_1.SetToolTip("Choose cyan color")
        sizer_color_stroke_1.Add(self.btn_col_stroke_7_1, 1, 0, 0)

        self.btn_col_stroke_8_1 = wx.Button(self.nb_panel_path, wx.ID_ANY, "Black")
        self.btn_col_stroke_8_1.SetMinSize((45, 45))
        self.btn_col_stroke_8_1.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.btn_col_stroke_8_1.SetFont(wx.Font(5, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.btn_col_stroke_8_1.SetToolTip("Choose black color")
        sizer_color_stroke_1.Add(self.btn_col_stroke_8_1, 1, 0, 0)

        sizer_fill_1 = wx.StaticBoxSizer(wx.StaticBox(self.nb_panel_path, wx.ID_ANY, "Fill"), wx.VERTICAL)
        sizer_path.Add(sizer_fill_1, 0, wx.EXPAND, 0)

        sizer_color_fill_1 = wx.StaticBoxSizer(wx.StaticBox(self.nb_panel_path, wx.ID_ANY, "Color"), wx.HORIZONTAL)
        sizer_fill_1.Add(sizer_color_fill_1, 1, wx.EXPAND, 0)

        self.btn_col_fill_1_1 = wx.Button(self.nb_panel_path, wx.ID_ANY, "None")
        self.btn_col_fill_1_1.SetMinSize((45, 45))
        self.btn_col_fill_1_1.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.btn_col_fill_1_1.SetFont(wx.Font(5, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_color_fill_1.Add(self.btn_col_fill_1_1, 1, 0, 0)

        self.btn_col_fill_2_1 = wx.Button(self.nb_panel_path, wx.ID_ANY, "Red")
        self.btn_col_fill_2_1.SetMinSize((45, 45))
        self.btn_col_fill_2_1.SetBackgroundColour(wx.Colour(255, 0, 0))
        self.btn_col_fill_2_1.SetFont(wx.Font(5, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_color_fill_1.Add(self.btn_col_fill_2_1, 1, 0, 0)

        self.btn_col_fill_3_1 = wx.Button(self.nb_panel_path, wx.ID_ANY, "Green")
        self.btn_col_fill_3_1.SetMinSize((45, 45))
        self.btn_col_fill_3_1.SetBackgroundColour(wx.Colour(0, 255, 0))
        self.btn_col_fill_3_1.SetFont(wx.Font(5, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_color_fill_1.Add(self.btn_col_fill_3_1, 1, 0, 0)

        self.btn_col_fill_4_1 = wx.Button(self.nb_panel_path, wx.ID_ANY, "Blue")
        self.btn_col_fill_4_1.SetMinSize((45, 45))
        self.btn_col_fill_4_1.SetBackgroundColour(wx.Colour(0, 0, 255))
        self.btn_col_fill_4_1.SetFont(wx.Font(5, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_color_fill_1.Add(self.btn_col_fill_4_1, 1, 0, 0)

        self.btn_col_fill_5_1 = wx.Button(self.nb_panel_path, wx.ID_ANY, "Yellow")
        self.btn_col_fill_5_1.SetMinSize((45, 45))
        self.btn_col_fill_5_1.SetBackgroundColour(wx.Colour(255, 255, 0))
        self.btn_col_fill_5_1.SetFont(wx.Font(5, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_color_fill_1.Add(self.btn_col_fill_5_1, 1, 0, 0)

        self.btn_col_fill_6_1 = wx.Button(self.nb_panel_path, wx.ID_ANY, "Pink")
        self.btn_col_fill_6_1.SetMinSize((45, 45))
        self.btn_col_fill_6_1.SetBackgroundColour(wx.Colour(255, 0, 255))
        self.btn_col_fill_6_1.SetFont(wx.Font(5, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_color_fill_1.Add(self.btn_col_fill_6_1, 1, 0, 0)

        self.btn_col_fill_7_1 = wx.Button(self.nb_panel_path, wx.ID_ANY, "Cyan")
        self.btn_col_fill_7_1.SetMinSize((45, 45))
        self.btn_col_fill_7_1.SetBackgroundColour(wx.Colour(0, 255, 255))
        self.btn_col_fill_7_1.SetFont(wx.Font(5, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_color_fill_1.Add(self.btn_col_fill_7_1, 1, 0, 0)

        self.btn_col_fill_8_1 = wx.Button(self.nb_panel_path, wx.ID_ANY, "Black")
        self.btn_col_fill_8_1.SetMinSize((45, 45))
        self.btn_col_fill_8_1.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.btn_col_fill_8_1.SetFont(wx.Font(5, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_color_fill_1.Add(self.btn_col_fill_8_1, 1, 0, 0)

        sizer_dimensions_1 = wx.StaticBoxSizer(wx.StaticBox(self.nb_panel_path, wx.ID_ANY, "Dimensions"), wx.VERTICAL)
        sizer_path.Add(sizer_dimensions_1, 0, wx.EXPAND, 0)

        sizer_dimensions_row_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_dimensions_1.Add(sizer_dimensions_row_1, 1, wx.EXPAND, 0)

        btn_dimension_col_1_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_dimensions_row_1.Add(btn_dimension_col_1_1, 0, wx.EXPAND, 0)

        label_16 = wx.StaticText(self.nb_panel_path, wx.ID_ANY, "X:")
        label_16.SetMinSize((-1, 23))
        btn_dimension_col_1_1.Add(label_16, 0, 0, 0)

        label_1 = wx.StaticText(self.nb_panel_path, wx.ID_ANY, "Width:")
        btn_dimension_col_1_1.Add(label_1, 0, 0, 0)

        btn_dimension_col_2_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_dimensions_row_1.Add(btn_dimension_col_2_1, 1, wx.EXPAND, 0)

        self.text_xpos_1 = wx.TextCtrl(self.nb_panel_path, wx.ID_ANY, "")
        btn_dimension_col_2_1.Add(self.text_xpos_1, 1, wx.EXPAND, 0)

        self.text_width_1 = wx.TextCtrl(self.nb_panel_path, wx.ID_ANY, "")
        btn_dimension_col_2_1.Add(self.text_width_1, 1, wx.EXPAND, 0)

        btn_dimension_col_3_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_dimensions_row_1.Add(btn_dimension_col_3_1, 0, wx.EXPAND, 0)

        label_17 = wx.StaticText(self.nb_panel_path, wx.ID_ANY, "Y:")
        label_17.SetMinSize((-1, 23))
        btn_dimension_col_3_1.Add(label_17, 0, 0, 0)

        label_3 = wx.StaticText(self.nb_panel_path, wx.ID_ANY, "Height:")
        label_3.SetMinSize((-1, 23))
        btn_dimension_col_3_1.Add(label_3, 0, 0, 0)

        btn_dimension_col_4_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_dimensions_row_1.Add(btn_dimension_col_4_1, 1, wx.EXPAND, 0)

        self.text_ypos_1 = wx.TextCtrl(self.nb_panel_path, wx.ID_ANY, "")
        btn_dimension_col_4_1.Add(self.text_ypos_1, 1, wx.EXPAND, 0)

        self.text_height_1 = wx.TextCtrl(self.nb_panel_path, wx.ID_ANY, "")
        btn_dimension_col_4_1.Add(self.text_height_1, 1, wx.EXPAND, 0)

        self.btn_lock_dimensions_1 = wx.ToggleButton(self.nb_panel_path, wx.ID_ANY, "")
        self.btn_lock_dimensions_1.SetMinSize((-1, 46))
        self.btn_lock_dimensions_1.SetBitmap(wx.Bitmap("D:\\_ENTWICKLUNG\\gui-files-meerk40t\\icons\\icons8-unlock-24.png", wx.BITMAP_TYPE_ANY))
        self.btn_lock_dimensions_1.SetBitmapPressed(wx.Bitmap("D:\\_ENTWICKLUNG\\gui-files-meerk40t\\icons\\icons8-lock-24.png", wx.BITMAP_TYPE_ANY))
        sizer_dimensions_row_1.Add(self.btn_lock_dimensions_1, 1, 0, 0)

        sizer_reset_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_path.Add(sizer_reset_1, 1, wx.EXPAND, 0)

        self.btn_reset_1 = wx.Button(self.nb_panel_path, wx.ID_ANY, "Undo user changes")
        self.btn_reset_1.SetToolTip("Undo all user changes")
        sizer_reset_1.Add(self.btn_reset_1, 0, 0, 0)

        self.nb_panel_img = wx.Panel(self.nb_properties, wx.ID_ANY)
        self.nb_properties.AddPage(self.nb_panel_img, "Image")

        sizer_image = wx.BoxSizer(wx.VERTICAL)

        sizer_img_1 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_image.Add(sizer_img_1, 0, wx.EXPAND, 0)

        label_7 = wx.StaticText(self.nb_panel_img, wx.ID_ANY, "DPP")
        label_7.SetMinSize((-1, 23))
        label_7.SetToolTip("Dots Per Pixel")
        sizer_img_1.Add(label_7, 1, 0, 0)

        self.spin_step_size = wx.SpinCtrl(self.nb_panel_img, wx.ID_ANY, "1", min=0, max=63)
        self.spin_step_size.SetMinSize((100, 23))
        self.spin_step_size.SetToolTip("Scan gap / step size image native value.")
        sizer_img_1.Add(self.spin_step_size, 5, 0, 0)

        sizer_img_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_image.Add(sizer_img_2, 0, wx.EXPAND, 0)

        label_8 = wx.StaticText(self.nb_panel_img, wx.ID_ANY, "DPI:")
        label_8.SetMinSize((-1, 23))
        label_8.SetToolTip("Dots Per Inch")
        sizer_img_2.Add(label_8, 1, 0, 0)

        self.combo_dpi = wx.ComboBox(self.nb_panel_img, wx.ID_ANY, choices=["1000", "500", "333", "250", "200", "166", "142", "125", "111", "100"], style=wx.CB_DROPDOWN)
        self.combo_dpi.SetSelection(0)
        sizer_img_2.Add(self.combo_dpi, 5, 0, 0)

        sizer_dimensions_3 = wx.StaticBoxSizer(wx.StaticBox(self.nb_panel_img, wx.ID_ANY, "Dimensions"), wx.VERTICAL)
        sizer_image.Add(sizer_dimensions_3, 0, wx.EXPAND, 0)

        sizer_dimensions_row_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_dimensions_3.Add(sizer_dimensions_row_3, 1, wx.EXPAND, 0)

        btn_dimension_col_1_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_dimensions_row_3.Add(btn_dimension_col_1_3, 0, wx.EXPAND, 0)

        label_20 = wx.StaticText(self.nb_panel_img, wx.ID_ANY, "X:")
        label_20.SetMinSize((-1, 23))
        btn_dimension_col_1_3.Add(label_20, 0, 0, 0)

        label_2 = wx.StaticText(self.nb_panel_img, wx.ID_ANY, "Width:")
        btn_dimension_col_1_3.Add(label_2, 0, 0, 0)

        btn_dimension_col_2_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_dimensions_row_3.Add(btn_dimension_col_2_3, 1, wx.EXPAND, 0)

        self.text_xpos_3 = wx.TextCtrl(self.nb_panel_img, wx.ID_ANY, "")
        btn_dimension_col_2_3.Add(self.text_xpos_3, 1, wx.EXPAND, 0)

        self.text_width_3 = wx.TextCtrl(self.nb_panel_img, wx.ID_ANY, "")
        btn_dimension_col_2_3.Add(self.text_width_3, 1, wx.EXPAND, 0)

        btn_dimension_col_3_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_dimensions_row_3.Add(btn_dimension_col_3_3, 0, wx.EXPAND, 0)

        label_27 = wx.StaticText(self.nb_panel_img, wx.ID_ANY, "Y:")
        label_27.SetMinSize((-1, 23))
        btn_dimension_col_3_3.Add(label_27, 0, 0, 0)

        label_6 = wx.StaticText(self.nb_panel_img, wx.ID_ANY, "Height:")
        label_6.SetMinSize((-1, 23))
        btn_dimension_col_3_3.Add(label_6, 0, 0, 0)

        btn_dimension_col_4_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_dimensions_row_3.Add(btn_dimension_col_4_3, 1, wx.EXPAND, 0)

        self.text_ypos_3 = wx.TextCtrl(self.nb_panel_img, wx.ID_ANY, "")
        btn_dimension_col_4_3.Add(self.text_ypos_3, 1, wx.EXPAND, 0)

        self.text_height_3 = wx.TextCtrl(self.nb_panel_img, wx.ID_ANY, "")
        btn_dimension_col_4_3.Add(self.text_height_3, 1, wx.EXPAND, 0)

        self.btn_lock_dimensions_2 = wx.ToggleButton(self.nb_panel_img, wx.ID_ANY, "")
        self.btn_lock_dimensions_2.SetMinSize((-1, 46))
        self.btn_lock_dimensions_2.SetBitmap(wx.Bitmap("D:\\_ENTWICKLUNG\\gui-files-meerk40t\\icons\\icons8-unlock-24.png", wx.BITMAP_TYPE_ANY))
        self.btn_lock_dimensions_2.SetBitmapPressed(wx.Bitmap("D:\\_ENTWICKLUNG\\gui-files-meerk40t\\icons\\icons8-lock-24.png", wx.BITMAP_TYPE_ANY))
        sizer_dimensions_row_3.Add(self.btn_lock_dimensions_2, 1, 0, 0)

        sizer_reset_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_image.Add(sizer_reset_2, 1, wx.EXPAND, 0)

        self.btn_reset_2 = wx.Button(self.nb_panel_img, wx.ID_ANY, "Undo user changes")
        self.btn_reset_2.SetToolTip("Undo all user changes")
        sizer_reset_2.Add(self.btn_reset_2, 0, 0, 0)

        self.nb_panel_group = wx.Panel(self.nb_properties, wx.ID_ANY)
        self.nb_properties.AddPage(self.nb_panel_group, "Group")

        sizer_group = wx.BoxSizer(wx.VERTICAL)

        sizer_id_2 = wx.StaticBoxSizer(wx.StaticBox(self.nb_panel_group, wx.ID_ANY, "Id"), wx.VERTICAL)
        sizer_group.Add(sizer_id_2, 0, wx.EXPAND, 0)

        self.text_id = wx.TextCtrl(self.nb_panel_group, wx.ID_ANY, "")
        sizer_id_2.Add(self.text_id, 0, wx.EXPAND, 0)

        sizer_label_2 = wx.StaticBoxSizer(wx.StaticBox(self.nb_panel_group, wx.ID_ANY, "Label"), wx.VERTICAL)
        sizer_group.Add(sizer_label_2, 0, wx.EXPAND, 0)

        self.text_label = wx.TextCtrl(self.nb_panel_group, wx.ID_ANY, "")
        sizer_label_2.Add(self.text_label, 0, wx.EXPAND, 0)

        sizer_dimensions_2 = wx.StaticBoxSizer(wx.StaticBox(self.nb_panel_group, wx.ID_ANY, "Dimensions"), wx.VERTICAL)
        sizer_group.Add(sizer_dimensions_2, 0, wx.EXPAND, 0)

        sizer_dimensions_row_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_dimensions_2.Add(sizer_dimensions_row_2, 1, wx.EXPAND, 0)

        btn_dimension_col_1_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_dimensions_row_2.Add(btn_dimension_col_1_2, 0, wx.EXPAND, 0)

        label_18 = wx.StaticText(self.nb_panel_group, wx.ID_ANY, "X:")
        label_18.SetMinSize((-1, 23))
        btn_dimension_col_1_2.Add(label_18, 0, 0, 0)

        label_4 = wx.StaticText(self.nb_panel_group, wx.ID_ANY, "Width:")
        btn_dimension_col_1_2.Add(label_4, 0, 0, 0)

        btn_dimension_col_2_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_dimensions_row_2.Add(btn_dimension_col_2_2, 1, wx.EXPAND, 0)

        self.text_xpos_2 = wx.TextCtrl(self.nb_panel_group, wx.ID_ANY, "")
        btn_dimension_col_2_2.Add(self.text_xpos_2, 1, wx.EXPAND, 0)

        self.text_width_2 = wx.TextCtrl(self.nb_panel_group, wx.ID_ANY, "")
        btn_dimension_col_2_2.Add(self.text_width_2, 1, wx.EXPAND, 0)

        btn_dimension_col_3_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_dimensions_row_2.Add(btn_dimension_col_3_2, 0, wx.EXPAND, 0)

        label_47 = wx.StaticText(self.nb_panel_group, wx.ID_ANY, "Y:")
        label_47.SetMinSize((-1, 23))
        btn_dimension_col_3_2.Add(label_47, 0, 0, 0)

        label_5 = wx.StaticText(self.nb_panel_group, wx.ID_ANY, "Height:")
        label_5.SetMinSize((-1, 23))
        btn_dimension_col_3_2.Add(label_5, 0, 0, 0)

        btn_dimension_col_4_2 = wx.BoxSizer(wx.VERTICAL)
        sizer_dimensions_row_2.Add(btn_dimension_col_4_2, 1, wx.EXPAND, 0)

        self.text_ypos_2 = wx.TextCtrl(self.nb_panel_group, wx.ID_ANY, "")
        btn_dimension_col_4_2.Add(self.text_ypos_2, 1, wx.EXPAND, 0)

        self.text_height_2 = wx.TextCtrl(self.nb_panel_group, wx.ID_ANY, "")
        btn_dimension_col_4_2.Add(self.text_height_2, 1, wx.EXPAND, 0)

        self.btn_lock_dimensions_4 = wx.ToggleButton(self.nb_panel_group, wx.ID_ANY, "")
        self.btn_lock_dimensions_4.SetMinSize((-1, 46))
        self.btn_lock_dimensions_4.SetBitmap(wx.Bitmap("D:\\_ENTWICKLUNG\\gui-files-meerk40t\\icons\\icons8-unlock-24.png", wx.BITMAP_TYPE_ANY))
        self.btn_lock_dimensions_4.SetBitmapPressed(wx.Bitmap("D:\\_ENTWICKLUNG\\gui-files-meerk40t\\icons\\icons8-lock-24.png", wx.BITMAP_TYPE_ANY))
        sizer_dimensions_row_2.Add(self.btn_lock_dimensions_4, 1, 0, 0)

        sizer_reset_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_group.Add(sizer_reset_4, 1, wx.EXPAND, 0)

        self.btn_reset_4 = wx.Button(self.nb_panel_group, wx.ID_ANY, "Undo user changes")
        self.btn_reset_4.SetToolTip("Undo all user changes")
        sizer_reset_4.Add(self.btn_reset_4, 0, 0, 0)

        self.nb_panel_text = wx.Panel(self.nb_properties, wx.ID_ANY)
        self.nb_properties.AddPage(self.nb_panel_text, "Text")

        sizer_text = wx.BoxSizer(wx.VERTICAL)

        sizer_3 = wx.StaticBoxSizer(wx.StaticBox(self.nb_panel_text, wx.ID_ANY, "Text"), wx.VERTICAL)
        sizer_text.Add(sizer_3, 1, wx.EXPAND, 0)

        self.text_text = wx.TextCtrl(self.nb_panel_text, wx.ID_ANY, "")
        sizer_3.Add(self.text_text, 0, wx.EXPAND, 0)

        sizer_font = wx.StaticBoxSizer(wx.StaticBox(self.nb_panel_text, wx.ID_ANY, "Font"), wx.HORIZONTAL)
        sizer_3.Add(sizer_font, 1, wx.EXPAND, 0)

        self.btn_choose_font = wx.Button(self.nb_panel_text, wx.ID_ANY, "Font")
        sizer_font.Add(self.btn_choose_font, 1, 0, 0)

        label_12 = wx.StaticText(self.nb_panel_text, wx.ID_ANY, "Size")
        sizer_font.Add(label_12, 0, 0, 0)

        self.combo_font_size = wx.ComboBox(self.nb_panel_text, wx.ID_ANY, choices=["5 pt", "7 pt", "8 pt", "9 pt", "10 pt", "11 pt", "12 pt", "14 pt"], style=wx.CB_DROPDOWN)
        sizer_font.Add(self.combo_font_size, 1, 0, 0)

        label_Preview = wx.StaticText(self.nb_panel_text, wx.ID_ANY, "< Preview >")
        label_Preview.SetFont(wx.Font(12, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_3.Add(label_Preview, 1, wx.EXPAND, 0)

        sizer_22 = wx.BoxSizer(wx.VERTICAL)
        sizer_text.Add(sizer_22, 1, wx.EXPAND, 0)

        sizer_2 = wx.StaticBoxSizer(wx.StaticBox(self.nb_panel_text, wx.ID_ANY, "Stroke"), wx.VERTICAL)
        sizer_22.Add(sizer_2, 1, wx.EXPAND, 0)

        sizer_color_stroke_2 = wx.StaticBoxSizer(wx.StaticBox(self.nb_panel_text, wx.ID_ANY, "Color"), wx.HORIZONTAL)
        sizer_2.Add(sizer_color_stroke_2, 1, wx.EXPAND, 0)

        self.btn_col_stroke_1_2 = wx.Button(self.nb_panel_text, wx.ID_ANY, "None")
        self.btn_col_stroke_1_2.SetMinSize((45, 45))
        self.btn_col_stroke_1_2.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.btn_col_stroke_1_2.SetFont(wx.Font(5, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.btn_col_stroke_1_2.SetToolTip("Choose no color")
        sizer_color_stroke_2.Add(self.btn_col_stroke_1_2, 1, 0, 0)

        self.btn_col_stroke_2_2 = wx.Button(self.nb_panel_text, wx.ID_ANY, "Red")
        self.btn_col_stroke_2_2.SetMinSize((45, 45))
        self.btn_col_stroke_2_2.SetBackgroundColour(wx.Colour(255, 0, 0))
        self.btn_col_stroke_2_2.SetFont(wx.Font(5, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.btn_col_stroke_2_2.SetToolTip("Choose red color")
        sizer_color_stroke_2.Add(self.btn_col_stroke_2_2, 1, 0, 0)

        self.btn_col_stroke_3_2 = wx.Button(self.nb_panel_text, wx.ID_ANY, "Green")
        self.btn_col_stroke_3_2.SetMinSize((45, 45))
        self.btn_col_stroke_3_2.SetBackgroundColour(wx.Colour(0, 255, 0))
        self.btn_col_stroke_3_2.SetFont(wx.Font(5, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.btn_col_stroke_3_2.SetToolTip("Choose green color")
        sizer_color_stroke_2.Add(self.btn_col_stroke_3_2, 1, 0, 0)

        self.btn_col_stroke_4_2 = wx.Button(self.nb_panel_text, wx.ID_ANY, "Blue")
        self.btn_col_stroke_4_2.SetMinSize((45, 45))
        self.btn_col_stroke_4_2.SetBackgroundColour(wx.Colour(0, 0, 255))
        self.btn_col_stroke_4_2.SetFont(wx.Font(5, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        self.btn_col_stroke_4_2.SetToolTip("Choose blue color")
        sizer_color_stroke_2.Add(self.btn_col_stroke_4_2, 1, 0, 0)

        self.btn_col_stroke_5_2 = wx.Button(self.nb_panel_text, wx.ID_ANY, "Yellow")
        self.btn_col_stroke_5_2.SetMinSize((45, 45))
        self.btn_col_stroke_5_2.SetBackgroundColour(wx.Colour(255, 255, 0))
        self.btn_col_stroke_5_2.SetFont(wx.Font(5, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.btn_col_stroke_5_2.SetToolTip("Choose yellow color")
        sizer_color_stroke_2.Add(self.btn_col_stroke_5_2, 1, 0, 0)

        self.btn_col_stroke_6_2 = wx.Button(self.nb_panel_text, wx.ID_ANY, "Pink")
        self.btn_col_stroke_6_2.SetMinSize((45, 45))
        self.btn_col_stroke_6_2.SetBackgroundColour(wx.Colour(255, 0, 255))
        self.btn_col_stroke_6_2.SetFont(wx.Font(5, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.btn_col_stroke_6_2.SetToolTip("Choose pink color")
        sizer_color_stroke_2.Add(self.btn_col_stroke_6_2, 1, 0, 0)

        self.btn_col_stroke_7_2 = wx.Button(self.nb_panel_text, wx.ID_ANY, "Cyan")
        self.btn_col_stroke_7_2.SetMinSize((45, 45))
        self.btn_col_stroke_7_2.SetBackgroundColour(wx.Colour(0, 255, 255))
        self.btn_col_stroke_7_2.SetFont(wx.Font(5, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.btn_col_stroke_7_2.SetToolTip("Choose cyan color")
        sizer_color_stroke_2.Add(self.btn_col_stroke_7_2, 1, 0, 0)

        self.btn_col_stroke_8_2 = wx.Button(self.nb_panel_text, wx.ID_ANY, "Black")
        self.btn_col_stroke_8_2.SetMinSize((45, 45))
        self.btn_col_stroke_8_2.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.btn_col_stroke_8_2.SetFont(wx.Font(5, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        self.btn_col_stroke_8_2.SetToolTip("Choose black color")
        sizer_color_stroke_2.Add(self.btn_col_stroke_8_2, 1, 0, 0)

        sizer_24 = wx.StaticBoxSizer(wx.StaticBox(self.nb_panel_text, wx.ID_ANY, "Fill"), wx.VERTICAL)
        sizer_22.Add(sizer_24, 0, wx.EXPAND, 0)

        sizer_color_fill_2 = wx.StaticBoxSizer(wx.StaticBox(self.nb_panel_text, wx.ID_ANY, "Color"), wx.HORIZONTAL)
        sizer_24.Add(sizer_color_fill_2, 1, wx.EXPAND, 0)

        self.btn_col_fill_1_2 = wx.Button(self.nb_panel_text, wx.ID_ANY, "None")
        self.btn_col_fill_1_2.SetMinSize((45, 45))
        self.btn_col_fill_1_2.SetBackgroundColour(wx.Colour(255, 255, 255))
        self.btn_col_fill_1_2.SetFont(wx.Font(5, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_color_fill_2.Add(self.btn_col_fill_1_2, 1, 0, 0)

        self.btn_col_fill_2_2 = wx.Button(self.nb_panel_text, wx.ID_ANY, "Red")
        self.btn_col_fill_2_2.SetMinSize((45, 45))
        self.btn_col_fill_2_2.SetBackgroundColour(wx.Colour(255, 0, 0))
        self.btn_col_fill_2_2.SetFont(wx.Font(5, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_color_fill_2.Add(self.btn_col_fill_2_2, 1, 0, 0)

        self.btn_col_fill_3_2 = wx.Button(self.nb_panel_text, wx.ID_ANY, "Green")
        self.btn_col_fill_3_2.SetMinSize((45, 45))
        self.btn_col_fill_3_2.SetBackgroundColour(wx.Colour(0, 255, 0))
        self.btn_col_fill_3_2.SetFont(wx.Font(5, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_color_fill_2.Add(self.btn_col_fill_3_2, 1, 0, 0)

        self.btn_col_fill_4_2 = wx.Button(self.nb_panel_text, wx.ID_ANY, "Blue")
        self.btn_col_fill_4_2.SetMinSize((45, 45))
        self.btn_col_fill_4_2.SetBackgroundColour(wx.Colour(0, 0, 255))
        self.btn_col_fill_4_2.SetFont(wx.Font(5, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, ""))
        sizer_color_fill_2.Add(self.btn_col_fill_4_2, 1, 0, 0)

        self.btn_col_fill_5_2 = wx.Button(self.nb_panel_text, wx.ID_ANY, "Yellow")
        self.btn_col_fill_5_2.SetMinSize((45, 45))
        self.btn_col_fill_5_2.SetBackgroundColour(wx.Colour(255, 255, 0))
        self.btn_col_fill_5_2.SetFont(wx.Font(5, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_color_fill_2.Add(self.btn_col_fill_5_2, 1, 0, 0)

        self.btn_col_fill_6_2 = wx.Button(self.nb_panel_text, wx.ID_ANY, "Pink")
        self.btn_col_fill_6_2.SetMinSize((45, 45))
        self.btn_col_fill_6_2.SetBackgroundColour(wx.Colour(255, 0, 255))
        self.btn_col_fill_6_2.SetFont(wx.Font(5, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_color_fill_2.Add(self.btn_col_fill_6_2, 1, 0, 0)

        self.btn_col_fill_7_2 = wx.Button(self.nb_panel_text, wx.ID_ANY, "Cyan")
        self.btn_col_fill_7_2.SetMinSize((45, 45))
        self.btn_col_fill_7_2.SetBackgroundColour(wx.Colour(0, 255, 255))
        self.btn_col_fill_7_2.SetFont(wx.Font(5, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_color_fill_2.Add(self.btn_col_fill_7_2, 1, 0, 0)

        self.btn_col_fill_8_2 = wx.Button(self.nb_panel_text, wx.ID_ANY, "Black")
        self.btn_col_fill_8_2.SetMinSize((45, 45))
        self.btn_col_fill_8_2.SetBackgroundColour(wx.Colour(0, 0, 0))
        self.btn_col_fill_8_2.SetFont(wx.Font(5, wx.FONTFAMILY_DEFAULT, wx.FONTSTYLE_NORMAL, wx.FONTWEIGHT_NORMAL, 0, "Segoe UI"))
        sizer_color_fill_2.Add(self.btn_col_fill_8_2, 1, 0, 0)

        sizer_dimensions_4 = wx.StaticBoxSizer(wx.StaticBox(self.nb_panel_text, wx.ID_ANY, "Dimensions"), wx.VERTICAL)
        sizer_22.Add(sizer_dimensions_4, 0, wx.EXPAND, 0)

        sizer_dimensions_row_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_dimensions_4.Add(sizer_dimensions_row_4, 1, wx.EXPAND, 0)

        btn_dimension_col_1_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_dimensions_row_4.Add(btn_dimension_col_1_4, 0, wx.EXPAND, 0)

        label_19 = wx.StaticText(self.nb_panel_text, wx.ID_ANY, "X:")
        label_19.SetMinSize((-1, 23))
        btn_dimension_col_1_4.Add(label_19, 0, 0, 0)

        label_9 = wx.StaticText(self.nb_panel_text, wx.ID_ANY, "Width:")
        btn_dimension_col_1_4.Add(label_9, 0, 0, 0)

        btn_dimension_col_2_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_dimensions_row_4.Add(btn_dimension_col_2_4, 1, wx.EXPAND, 0)

        self.text_xpos_4 = wx.TextCtrl(self.nb_panel_text, wx.ID_ANY, "")
        btn_dimension_col_2_4.Add(self.text_xpos_4, 1, wx.EXPAND, 0)

        self.text_width_4 = wx.TextCtrl(self.nb_panel_text, wx.ID_ANY, "")
        btn_dimension_col_2_4.Add(self.text_width_4, 1, wx.EXPAND, 0)

        btn_dimension_col_3_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_dimensions_row_4.Add(btn_dimension_col_3_4, 0, wx.EXPAND, 0)

        label_97 = wx.StaticText(self.nb_panel_text, wx.ID_ANY, "Y:")
        label_97.SetMinSize((-1, 23))
        btn_dimension_col_3_4.Add(label_97, 0, 0, 0)

        label_10 = wx.StaticText(self.nb_panel_text, wx.ID_ANY, "Height:")
        label_10.SetMinSize((-1, 23))
        btn_dimension_col_3_4.Add(label_10, 0, 0, 0)

        btn_dimension_col_4_4 = wx.BoxSizer(wx.VERTICAL)
        sizer_dimensions_row_4.Add(btn_dimension_col_4_4, 1, wx.EXPAND, 0)

        self.text_ypos_4 = wx.TextCtrl(self.nb_panel_text, wx.ID_ANY, "")
        btn_dimension_col_4_4.Add(self.text_ypos_4, 1, wx.EXPAND, 0)

        self.text_height_4 = wx.TextCtrl(self.nb_panel_text, wx.ID_ANY, "")
        btn_dimension_col_4_4.Add(self.text_height_4, 1, wx.EXPAND, 0)

        self.btn_lock_dimensions_3 = wx.ToggleButton(self.nb_panel_text, wx.ID_ANY, "")
        self.btn_lock_dimensions_3.SetMinSize((-1, 46))
        self.btn_lock_dimensions_3.SetBitmap(wx.Bitmap("D:\\_ENTWICKLUNG\\gui-files-meerk40t\\icons\\icons8-unlock-24.png", wx.BITMAP_TYPE_ANY))
        self.btn_lock_dimensions_3.SetBitmapPressed(wx.Bitmap("D:\\_ENTWICKLUNG\\gui-files-meerk40t\\icons\\icons8-lock-24.png", wx.BITMAP_TYPE_ANY))
        sizer_dimensions_row_4.Add(self.btn_lock_dimensions_3, 1, 0, 0)

        sizer_reset_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_text.Add(sizer_reset_3, 1, wx.EXPAND, 0)

        self.btn_reset_3 = wx.Button(self.nb_panel_text, wx.ID_ANY, "Undo user changes")
        self.btn_reset_3.SetToolTip("Undo all user changes")
        sizer_reset_3.Add(self.btn_reset_3, 0, 0, 0)

        self.nb_properties_Empty = wx.Panel(self.nb_properties, wx.ID_ANY)
        self.nb_properties.AddPage(self.nb_properties_Empty, "Empty")

        sizer_25 = wx.BoxSizer(wx.HORIZONTAL)

        label_11 = wx.StaticText(self.nb_properties_Empty, wx.ID_ANY, "No Element(s) selected")
        sizer_25.Add(label_11, 1, wx.ALIGN_CENTER_VERTICAL, 0)

        self.nb_properties_Empty.SetSizer(sizer_25)

        self.nb_panel_text.SetSizer(sizer_text)

        self.nb_panel_group.SetSizer(sizer_group)

        self.nb_panel_img.SetSizer(sizer_image)

        self.nb_panel_path.SetSizer(sizer_path)

        self.panel_properties.SetSizer(sizer_main)

        self.Layout()

        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_stroke_color, self.btn_col_stroke_1_1)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_stroke_color, self.btn_col_stroke_2_1)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_stroke_color, self.btn_col_stroke_3_1)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_stroke_color, self.btn_col_stroke_4_1)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_stroke_color, self.btn_col_stroke_5_1)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_stroke_color, self.btn_col_stroke_6_1)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_stroke_color, self.btn_col_stroke_7_1)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_stroke_color, self.btn_col_stroke_8_1)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_fill_color, self.btn_col_fill_1_1)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_fill_color, self.btn_col_fill_2_1)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_fill_color, self.btn_col_fill_3_1)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_fill_color, self.btn_col_fill_4_1)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_fill_color, self.btn_col_fill_5_1)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_fill_color, self.btn_col_fill_6_1)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_fil_color, self.btn_col_fill_8_1)
        self.Bind(wx.EVT_TEXT_ENTER, self.on_text_dimension_enter, self.text_xpos_1)
        self.Bind(wx.EVT_TEXT_ENTER, self.on_text_dimension_enter, self.text_width_1)
        self.Bind(wx.EVT_TEXT_ENTER, self.on_text_dimension_enter, self.text_ypos_1)
        self.Bind(wx.EVT_TEXT_ENTER, self.on_text_dimension_enter, self.text_height_1)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.on_evt_btn_lock_dimensions, self.btn_lock_dimensions_1)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_reset, self.btn_reset_1)
        self.Bind(wx.EVT_SPINCTRL, self.on_spin_step, self.spin_step_size)
        self.Bind(wx.EVT_TEXT_ENTER, self.on_spin_step, self.spin_step_size)
        self.Bind(wx.EVT_COMBOBOX, self.on_combo_dpi, self.combo_dpi)
        self.Bind(wx.EVT_TEXT_ENTER, self.on_text_dimension_enter, self.text_xpos_3)
        self.Bind(wx.EVT_TEXT_ENTER, self.on_text_dimension_enter, self.text_width_3)
        self.Bind(wx.EVT_TEXT_ENTER, self.on_text_dimension_enter, self.text_ypos_3)
        self.Bind(wx.EVT_TEXT_ENTER, self.on_text_dimension_enter, self.text_height_3)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.on_evt_btn_lock_dimensions, self.btn_lock_dimensions_2)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_reset, self.btn_reset_2)
        self.Bind(wx.EVT_TEXT, self.on_text_id_change, self.text_id)
        self.Bind(wx.EVT_TEXT_ENTER, self.on_text_id_change, self.text_id)
        self.Bind(wx.EVT_TEXT, self.on_text_label_change, self.text_label)
        self.Bind(wx.EVT_TEXT_ENTER, self.on_text_label_change, self.text_label)
        self.Bind(wx.EVT_TEXT_ENTER, self.on_text_dimension_enter, self.text_xpos_2)
        self.Bind(wx.EVT_TEXT_ENTER, self.on_text_dimension_enter, self.text_width_2)
        self.Bind(wx.EVT_TEXT_ENTER, self.on_text_dimension_enter, self.text_ypos_2)
        self.Bind(wx.EVT_TEXT_ENTER, self.on_text_dimension_enter, self.text_height_2)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.on_evt_btn_lock_dimensions, self.btn_lock_dimensions_4)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_reset, self.btn_reset_4)
        self.Bind(wx.EVT_TEXT, self.on_text_name_change, self.text_text)
        self.Bind(wx.EVT_TEXT_ENTER, self.on_text_name_change, self.text_text)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_stroke_color, self.btn_col_stroke_1_2)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_stroke_color, self.btn_col_stroke_2_2)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_stroke_color, self.btn_col_stroke_3_2)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_stroke_color, self.btn_col_stroke_4_2)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_stroke_color, self.btn_col_stroke_5_2)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_stroke_color, self.btn_col_stroke_6_2)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_stroke_color, self.btn_col_stroke_7_2)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_stroke_color, self.btn_col_stroke_8_2)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_fill_color, self.btn_col_fill_1_2)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_fill_color, self.btn_col_fill_2_2)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_fill_color, self.btn_col_fill_3_2)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_fill_color, self.btn_col_fill_4_2)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_fill_color, self.btn_col_fill_5_2)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_fill_color, self.btn_col_fill_6_2)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_fil_color, self.btn_col_fill_8_2)
        self.Bind(wx.EVT_TEXT_ENTER, self.on_text_dimension_enter, self.text_xpos_4)
        self.Bind(wx.EVT_TEXT_ENTER, self.on_text_dimension_enter, self.text_width_4)
        self.Bind(wx.EVT_TEXT_ENTER, self.on_text_dimension_enter, self.text_ypos_4)
        self.Bind(wx.EVT_TEXT_ENTER, self.on_text_dimension_enter, self.text_height_4)
        self.Bind(wx.EVT_TOGGLEBUTTON, self.on_evt_btn_lock_dimensions, self.btn_lock_dimensions_3)
        self.Bind(wx.EVT_BUTTON, self.on_evt_btn_reset, self.btn_reset_3)
        # end wxGlade

    def on_evt_btn_stroke_color(self, event):  # wxGlade: ElemProprties.<event_handler>
        print("Event handler 'on_evt_btn_stroke_color' not implemented!")
        event.Skip()

    def on_evt_btn_fill_color(self, event):  # wxGlade: ElemProprties.<event_handler>
        print("Event handler 'on_evt_btn_fill_color' not implemented!")
        event.Skip()

    def on_evt_btn_fil_color(self, event):  # wxGlade: ElemProprties.<event_handler>
        print("Event handler 'on_evt_btn_fil_color' not implemented!")
        event.Skip()

    def on_text_dimension_enter(self, event):  # wxGlade: ElemProprties.<event_handler>
        print("Event handler 'on_text_dimension_enter' not implemented!")
        event.Skip()

    def on_evt_btn_lock_dimensions(self, event):  # wxGlade: ElemProprties.<event_handler>
        print("Event handler 'on_evt_btn_lock_dimensions' not implemented!")
        event.Skip()

    def on_evt_btn_reset(self, event):  # wxGlade: ElemProprties.<event_handler>
        print("Event handler 'on_evt_btn_reset' not implemented!")
        event.Skip()

    def on_spin_step(self, event):  # wxGlade: ElemProprties.<event_handler>
        print("Event handler 'on_spin_step' not implemented!")
        event.Skip()

    def on_combo_dpi(self, event):  # wxGlade: ElemProprties.<event_handler>
        print("Event handler 'on_combo_dpi' not implemented!")
        event.Skip()

    def on_text_id_change(self, event):  # wxGlade: ElemProprties.<event_handler>
        print("Event handler 'on_text_id_change' not implemented!")
        event.Skip()

    def on_text_label_change(self, event):  # wxGlade: ElemProprties.<event_handler>
        print("Event handler 'on_text_label_change' not implemented!")
        event.Skip()

    def on_text_name_change(self, event):  # wxGlade: ElemProprties.<event_handler>
        print("Event handler 'on_text_name_change' not implemented!")
        event.Skip()

# end of class ElemProprties

class dlg_Property(wx.App):
    def OnInit(self):
        self.frame_Properties = ElemProprties(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame_Properties)
        self.frame_Properties.Show()
        return True

# end of class dlg_Property

if __name__ == "__main__":
    MK_Property = dlg_Property(0)
    MK_Property.MainLoop()
